// Each Basic F2L case's masked state as caseState() computed it at commit 104af38,
// before the F2L mask was generalized: the 54 facelets in cube.ts order, "."
// for gray. Frozen: the generalized mask is proven to leave Basic unchanged
// only if this text never changes, so never regenerate it.
export const BASIC_MASKS: Readonly<Record<string, string>> = {
  "f2l-easy-1": ".....F..FRR..R..R...D.F..F..D.DDD.D.....L..L.....B..B.",
  "f2l-easy-2": "...F..F......R..R.D...F..F..D.DDD.D..LL.L..L.....B..B.",
  "f2l-easy-3": ".F......RD...R..R...F.F..F..D.DDD.D.....L..L..R..B..B.",
  "f2l-easy-4": ".F....L......R..R.F...F..F..D.DDD.D...D.L..L..L..B..B.",
  "f2l-disconnected-1": ".F......FR...R..R...D.F..F..D.DDD.D.....L..L..R..B..B.",
  "f2l-disconnected-2": "...F....FR...R..R...D.F..F..D.DDD.D..R..L..L.....B..B.",
  "f2l-disconnected-3": "...F....RD...R..R...F.F..F..D.DDD.D..R..L..L.....B..B.",
  "f2l-disconnected-4": ".F......DF...R..R...R.F..F..D.DDD.D.....L..L..R..B..B.",
  "f2l-disconnected-5": "...F....DF...R..R...R.F..F..D.DDD.D..R..L..L.....B..B.",
  "f2l-disconnected-6": ".F....F......R..R.D...F..F..D.DDD.D...L.L..L..L..B..B.",
  "f2l-disconnected-7": ".....FF...L..R..R.D...F..F..D.DDD.D...L.L..L.....B..B.",
  "f2l-disconnected-8": ".....FL...L..R..R.F...F..F..D.DDD.D...D.L..L.....B..B.",
  "f2l-disconnected-9": ".F....D......R..R.L...F..F..D.DDD.D...F.L..L..L..B..B.",
  "f2l-disconnected-10": ".....FD...L..R..R.L...F..F..D.DDD.D...F.L..L.....B..B.",
  "f2l-corner-1": ".....F....R..R.RR.....F..FF.DDDDD.D.....L..L.....B..B.",
  "f2l-corner-2": ".....F....R..R.FR.....F..FD.DRDDD.D.....L..L.....B..B.",
  "f2l-corner-3": ".....F....R..R.DR.....F..FR.DFDDD.D.....L..L.....B..B.",
  "f2l-corner-4": "...F.........R..R.....F.FF.DD.DDD.D..L..L..LL....B..B.",
  "f2l-corner-5": "...F.........R..R.....F.DF.LD.DDD.D..L..L..LF....B..B.",
  "f2l-corner-6": "...F.........R..R.....F.LF.FD.DDD.D..L..L..LD....B..B.",
  "f2l-edge-1": "........DF..RR..R...R.FF.F..D.DDD.D.....L..L.....B..B.",
  "f2l-edge-2": "........DF..FR..R...R.FR.F..D.DDD.D.....L..L.....B..B.",
  "f2l-edge-3": "........FR..RR..R...D.FF.F..D.DDD.D.....L..L.....B..B.",
  "f2l-edge-4": "........RD..RR..R...F.FF.F..D.DDD.D.....L..L.....B..B.",
  "f2l-edge-5": "........FR..FR..R...D.FR.F..D.DDD.D.....L..L.....B..B.",
  "f2l-edge-6": "........RD..FR..R...F.FR.F..D.DDD.D.....L..L.....B..B.",
  "f2l-connected-1": ".......FRD...R..R..RF.F..F..D.DDD.D.....L..L.....B..B.",
  "f2l-connected-2": ".....F..RDR..R..R...F.F..F..D.DDD.D.....L..L.....B..B.",
  "f2l-connected-3": ".......FFR...R..R..RD.F..F..D.DDD.D.....L..L.....B..B.",
  "f2l-connected-4": ".....F..DFR..R..R...R.F..F..D.DDD.D.....L..L.....B..B.",
  "f2l-connected-5": ".......FDF...R..R..RR.F..F..D.DDD.D.....L..L.....B..B.",
  "f2l-connected-6": "......LF.....R..R.FL..F..F..D.DDD.D...D.L..L.....B..B.",
  "f2l-connected-7": "...F..L......R..R.F...F..F..D.DDD.D..LD.L..L.....B..B.",
  "f2l-connected-8": "......FF.....R..R.DL..F..F..D.DDD.D...L.L..L.....B..B.",
  "f2l-connected-9": "...F..D......R..R.L...F..F..D.DDD.D..LF.L..L.....B..B.",
  "f2l-connected-10": "......DF.....R..R.LL..F..F..D.DDD.D...F.L..L.....B..B.",
  "f2l-slot-1": "............RR.FR.....FF.FD.DRDDD.D.....L..L.....B..B.",
  "f2l-slot-2": "............RR.DR.....FF.FR.DFDDD.D.....L..L.....B..B.",
  "f2l-slot-3": "............FR.FR.....FR.FD.DRDDD.D.....L..L.....B..B.",
  "f2l-slot-4": "............FR.DR.....FR.FR.DFDDD.D.....L..L.....B..B.",
  "f2l-slot-5": "............FR.RR.....FR.FF.DDDDD.D.....L..L.....B..B.",
};
